// <auto-generated />
namespace BonjourApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class lift : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lift));
        
        string IMigrationMetadata.Id
        {
            get { return "201505292041223_lift"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
